const ACTIONS = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ROLES: 'GET_ROLES',
    GET_BOARDS: 'GET_BOARDS',
    GET_FAVORITE_BOARDS: 'GET_FAVORITE_BOARDS',
    GET_USERS_SELECTION: 'GET_USERS_SELECTION'
}

export default ACTIONS