const ACTIONS = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ROLES: 'GET_ROLES',
    GET_BOARDS: 'GET_BOARDS',
    GET_FAVORITE_BOARDS: 'GET_FAVORITE_BOARDS',
    GET_USERS_SELECTION: 'GET_USERS_SELECTION',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_ISP: 'GET_ALL_ISP',
    GET_INTERNET_SERVICES: 'GET_INTERNET_SERVICES',
    GET_ACTIVE_INTERNET_SERVICES: 'GET_ACTIVE_INTERNET_SERVICES',
    GET_ALL_LOCATIONS: 'GET_ALL_LOCATIONS',
    GET_ACTIVE_LOCATIONS: 'GET_ACTIVE_LOCATIONS',
    GET_ALL_CUSTOMERS: 'GET_ALL_CUSTOMERS',
    GET_ACTIVE_CUSTOMERS: 'GET_ACTIVE_CUSTOMERS',
    GET_CUSTOMERS_SUBSCRIPTIONS: 'GET_CUSTOMERS_SUBSCRIPTIONS',
    GET_SUBSCRIPTION_INVOICES: 'GET_SUBSCRIPTION_INVOICES',
    
}

export default ACTIONS